[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gameoflife_serveur"
version = "0.0.1"
dependencies = [
    "flask",
    "flask_socketio",
    "flask_cors",
    "mysql-connector-python"]

