[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dao", "modele", "entites", "services, tests"]

[project]
name = "gameoflife_serveur"
version = "0.0.1"
dependencies = [
    "flask",
    "flask_socketio",
    "flask_cors"]

